### PR TITLE
Add template universe annotations

### PR DESCRIPTION
**Pull request by palmskog**
Coq master recently introduced template universe annotations for constructs like `Inductive` and `Record`. This PR adds those annotations where necessary (so that no warnings are raised). Also includes the license fixes from #10.

### CODE REVIEW

**Comment by Zimmi48** [comment]
@SkySkimmer is the one who introduced these annotations and therefore will be able to explain the intent better but I think his intention was to encourage users to rely less often on template polymorphism by turning the ` Template Polymorphism Auto` option off (which will become the default in the future). Obviously, this is a compatibility breaking change whereas adding the template polymorphism attributes is not (since it doesn't change the semantics). Therefore, it may not always be a good idea for older projects to stop making their inductive types template polymorphic.

**Comment by palmskog** [comment]
@Zimmi48 I was basically following the lead from @SkySkimmer in coq-community/aac-tactics#27. I'm not sure I understand what the bottom line is here for Coq-community projects. For libraries, it's obvious that we can't break compatibility, and there we just add `-arg -w -arg -auto-template` into `_CoqProject`. But for plugins (where we can change `master` without bothering about compatibility) it's much less clear. 

@SkySkimmer can you give some recommendation for plugin projects in general whether annotations should be added or not?

**Comment by SkySkimmer** [comment]
I did the aac-tactics patch because they error on warnings, but disabling the warning may be legitimate too. The question is how aware do you want to be of what types are template poly.
It's impossible to annotate plugins since they're ml code.

**Comment by SkySkimmer** [comment]
Generally I would want to annotate everything, disable the auto template option, then look through the annotations and remove the ones you don't want.
This can be a pain if you don't have infrastructure to set project-wide options though :( (coq/coq#9295)

**Comment by palmskog** [comment]
I may have been unclear above. Basically, we can do backward-incompatible changes to `.v` files in plugin projects, since `master` doesn't have to work with, say, 8.8.

Is there some simple criterion for an annotation one wouldn't want? Maybe an example?

**Comment by Zimmi48** [comment]
>then look through the annotations and remove the ones you don't want

That's the part that is not obvious to a Coq user who is not used to think about universes.

**Comment by SkySkimmer** [comment]
Maybe we should default-disable the warning until https://github.com/coq/coq/issues/9296 is fixed.

**Comment by palmskog** [comment]
OK, I will just close this PR for now and do the license fix (with template warning supressed) separately. I'll leave the branch alive for now, and I will rebase it later if there is a stronger consensus what to do.

**Comment by tchajed** [comment]
I would think nothing in ATBR needs to be template universe polymorphic and would happily disable `Auto Template Polymorphism` if we could do it without a global option, in anticipation of Coq changing the default.

I prefer to stay away from universes by default until there's a need, and the ecosystem is small enough that if somebody cares about polymorphism we could just change the library and deal with clients individually. In the long term Coq may need a better story for universes (eg, currently there's no universe polymorphic standard library), but if it doesn't affect this library internally I'm happy to export a conservative interface (that is, a universe monomorphic one).

**Comment by herbelin** [comment]
> eg, currently there's no universe polymorphic standard library

There is universe polymorphism in the standard library! Inductive types are polymorphic over their type parameters and this is useful for types such as `list`, `sig`, `sigT`. The compilation of the standard library fails if we make them monomorphic.

**Comment by tchajed** [comment]
Yes, all of those types are template universe polymorphic; I meant they aren't polymorphic inductives.

**Comment by herbelin** [comment]
> I meant they aren't polymorphic inductives.

Ah, ok, there was a misunderstanding. But template polymorphism is basically a particular case of fully-fledged universe polymorphism and it seems that we are going towards transparently get the effect of template polymorphism by using the general infrastructure of fully-fledged polymorphism (i.e. the internal infrastructure with explicit abstraction and application over universes). This is why, sorry, I misunderstood your words.

**Pull request closed without merging**
