### PR TITLE
Update reification plugin for upstream API changes

### PR DESCRIPTION
**Pull request by tchajed**
Tested with coq/coq@92d1a0c14ef32.

### CODE REVIEW

**Comment by Zimmi48** [comment]
@tchajed Reiterating my invitation from coq/opam-coq-archive#415 to become the principal maintainer of this contrib within coq-community. We can then setup some continuous integration like we did for other projects maintained there. This should help detecting breakages. Maybe the process of opening an issue at https://github.com/coq-community/manifesto/issues/new?template=move_project.md is a bit too heavy (this is mainly to advertise the move to other interested people) so let's skip it if you want. Just say the word and I'll transfer the repository and make you a member of the organization.

**Comment by tchajed** [comment]
Yup, thanks for the reminder and the link - I went ahead and made an issue.

I think there's a followup library that basically supersedes ATBR but the project website and Coq package list are down (coq/opam-coq-archive#508), and in any case I don't think I have time to deal with that right now.

**Comment by Zimmi48** [comment]
OK, if you or someone else do(es) have time later on, it could maybe be worth consolidating the two.

**Comment by herbelin** [comment]
Anyway, I'm merging in the meantime.

**Comment by Zimmi48** [comment]
@herbelin Sure, go ahead, although @tchajed note that you could have merged this PR yourself since you now have control over this repo.

**Comment by Zimmi48** [comment]
It seems that I have involuntarily discouraged @herbelin to merge this PR :confused: 

BTW, @tchajed, you might want to add yourself to the watch list of this repo so that you are aware of incoming pull requests.

**Pull request merged**
