### PR TITLE
Fix deprecations and warnings for 8.9, add CI

### PR DESCRIPTION
**Pull request by palmskog**
This PR brings in improvements from `master`, such as CI, to the `v8.9` branch. It also fixes deprecations and warnings when deemed possible, and supresses the rest in `_CoqProject`.

### CODE REVIEW

**Comment by tchajed** [comment]
Thanks for fixing these issues!

Do you know what happened to the nix build (failing [Job #6.1](https://travis-ci.com/coq-community/atbr/jobs/163831422))? Other than that this looks good.

**Comment by palmskog** [comment]
The problem is NixOS/nixpkgs#51325 still not having been merged. Added a workaround. This is a non-Coq-master CI problem.

**Comment by palmskog** [comment]
@tchajed this should be ready to merge now, unless you have some requested changes.

**Comment by tchajed** [comment]
Thanks!

**Pull request merged**
